name: '🧪 PRE-release'

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest 
    if: github.ref == 'refs/heads/master'

    steps:
      
      - name: 🆔 Get latest run ID
        id: runid
        run: |
          run_id=$(curl --request GET \
            --url https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/runs \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            | jq '.workflow_runs[] | select(.status=="completed") | .id' | head -1)
          echo "::set-output name=run-id::$run_id"

      - name: ⬇️ Download binary output from build.yml
        uses: actions/download-artifact@v4
        with:
          name: managed
          path: .
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.runid.outputs.run-id }}

      - name: debug
        run: ls -R

      - name: 🔢 prep release notes
        run: |
          grep -m 2 -B 1000 '^## ' docs/release-notes.md | tail -n +3 | head -n -2 > final_notes.md
          cat final_notes.md

      # - name: 📦 Publish to NuGet
      #   run: dotnet nuget push managed/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

